require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-sorbet

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - node_modules/**/*
    - bin/bundle
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Exclude:
    - app/components/**
