version: '3.6'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: h2
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
