version: '3.6'

services:
  app:
    build: &build
      context: .
      dockerfile: docker/Dockerfile
      args:
        SECRET_KEY_BASE: 2e4f669b6529a0bcec468d9b5329e2fe7e7f6a4d7915370862d6d4f2b6907f1fabc505a681aaa13b3858f02588602fd0b721ca783bdac37fe70ea83b8f123456
    environment: &environment
      DATABASE_NAME: h2
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOSTNAME: db
      RAILS_SERVE_STATIC_FILES: 'true'
      REDIS_URL: redis://redis:6379/ # for ActionCable
      REMOTE_USER: auser@stanford.edu
      ROLES: dlss:hydrus-app-administrators
      LOCAL_DOCKER: 'true'
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - workers
    command: "./docker/invoke-app.sh"
  workers:
    build: *build
    environment: *environment
    depends_on:
      - db
      - redis
    command: "./docker/invoke-worker.sh"
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: h2
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
