version: '3.6'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: h2
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
